name = "gaveta"
version = "0.1.0"
licences = ["MIT"]
description = "Vanilla utility functions for different projects."
gleam = ">= 1.16.0"

[dependencies]
gleam_stdlib = ">= 1.0.2 and < 2.0.0"

[dev_dependencies]
gleeunit = "== 1.10.0"

[repository]
type = "github"
user = "joaopalmeiro"
repo = "gaveta-gleam"
